add_executable(hum src/app/main.cpp)
target_include_directories(hum PRIVATE ${HUM_GENERATED_DIR})
add_dependencies(hum hum_build_id)
target_link_libraries(hum PRIVATE hum_core)
# The add-on list is generated so no source file names a pack.
set(HUM_ADDON_DECLS "")
set(HUM_ADDON_CALLS "")
set(HUM_ADDON_IDS "")
foreach(addon ${HUM_ADDON_PACKS})
  target_link_libraries(hum PRIVATE hum_pack_${addon})
  string(APPEND HUM_ADDON_DECLS "void hum_register_pack_${addon}(Registry&);\n")
  string(APPEND HUM_ADDON_CALLS "    hum_register_pack_${addon}(Registry::instance());\n")
  list(APPEND HUM_ADDON_IDS "\"${addon}\"")
endforeach()
list(JOIN HUM_ADDON_IDS ", " HUM_ADDON_IDS)
configure_file(${CMAKE_CURRENT_SOURCE_DIR}/cmake/AddonPacks.h.in
               ${HUM_GENERATED_DIR}/hum_addon_packs.h @ONLY)
if(HUM_ADDON_PACKS)
  target_compile_definitions(hum PRIVATE HUM_STATIC_ADDON_PACKS=1)
endif()
if(HUM_LIVE_AUDIO)
  target_link_libraries(hum PRIVATE juce::juce_audio_devices)
  target_compile_definitions(hum PRIVATE HUM_LIVE_AUDIO=1)
endif()
