add_library(hum_core STATIC
  src/core/graph/AudioGraph.cpp
  src/core/graph/AudioGraphLatency.cpp
  src/core/graph/AudioGraphModulation.cpp
  src/core/graph/AudioGraphTuning.cpp
  src/core/graph/AudioGraphMidi.cpp
  src/core/net/LicenseCheck.cpp
  src/core/packs/Registry.cpp
  src/core/packs/BuiltinPacks.cpp
  src/core/params/ParamSchema.cpp
  src/core/params/ParamUnit.cpp
  src/core/packs/Categories.cpp
  src/core/midi/RiffImport.cpp
  src/core/midi/RiffImportMidi.cpp
  src/core/midi/MidiClipImport.cpp
  src/core/packs/PackManifest.cpp
  src/core/packs/PackRegistry.cpp
  src/core/packs/Roles.cpp
  src/core/packs/PackLoader.cpp
  src/core/packs/PackUpdates.cpp
  src/core/plugins/PluginHost.cpp
  src/core/plugins/PluginListStore.cpp
  src/core/tuning/ScaleLibrary.cpp
  src/core/tuning/MtsTuning.cpp
  src/core/tuning/TuningProbe.cpp
  src/core/tuning/TuningProbeStore.cpp
  src/core/plugins/HostedPlugin.cpp
  src/core/plugins/PluginScanner.cpp
  src/core/plugins/ProcessId.cpp
  src/core/plugins/BridgeRing.cpp
  src/core/plugins/BridgeClient.cpp
  src/core/plugins/BridgeWorker.cpp
  src/core/plugins/BridgedPlugin.cpp
  src/core/analysis/BeatDetector.cpp
  src/core/analysis/KeyDetector.cpp
  src/core/assistant/PresetGenie.cpp
  src/core/assistant/AssistantProtocol.cpp
  src/core/assistant/OllamaWire.cpp
  src/core/assistant/RecipeSynth.cpp
  src/io/MidiExport.cpp
  src/io/PatchWriter.cpp
  src/io/PatchWriterElements.cpp
  src/io/PatchDocument.cpp
  src/io/PatchDocumentPattern.cpp
  src/io/PatchLoader.cpp
  src/io/SignalFile.cpp
  src/io/WavWriter.cpp
  src/io/Mp3Writer.cpp
  src/io/AutosaveStore.cpp
)
target_include_directories(hum_core PUBLIC src)
target_compile_definitions(hum_core PUBLIC
  HUM_PACKS_DIR="${CMAKE_CURRENT_SOURCE_DIR}/../packs")
target_link_libraries(hum_core PUBLIC
  monocypher
  mp3lame
  ableton_link
  hum_sdk
  hum_pack_core
  hum_pack_humus
  hum_pack_av
  juce::juce_core
  juce::juce_audio_basics
  juce::juce_audio_formats
  juce::juce_audio_processors
  juce::juce_dsp
  juce::juce_osc
)
if(APPLE)
  target_link_libraries(hum_core PUBLIC "-framework CoreAudioKit")
  target_link_libraries(hum_core PUBLIC "-framework GameController")
endif()
