# Discovered, not listed: a pack directory declares HUM_PACK_ROLE and builds
# hum_pack_<dir>, so a tree without an add-on builds without it.
set(HUM_BUILTIN_PACKS "")
set(HUM_ADDON_PACKS "")
file(GLOB HUM_PACK_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/../packs/*)
list(SORT HUM_PACK_DIRS)
foreach(pack_dir ${HUM_PACK_DIRS})
  if(NOT EXISTS ${pack_dir}/CMakeLists.txt)
    continue()
  endif()
  get_filename_component(pack_name ${pack_dir} NAME)
  set(HUM_PACK_ROLE "")
  add_subdirectory(${pack_dir} pack_${pack_name})
  if("${HUM_PACK_ROLE}" STREQUAL "builtin")
    list(APPEND HUM_BUILTIN_PACKS ${pack_name})
  elseif("${HUM_PACK_ROLE}" STREQUAL "addon")
    list(APPEND HUM_ADDON_PACKS ${pack_name})
  endif()
endforeach()
